//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMH
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONDATHANG
    {
        public int MaDH { get; set; }
        public string MaNV { get; set; }
        public string MaNCC { get; set; }
        public string TeNDH { get; set; }
        public Nullable<System.DateTime> NgayDAT { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> TongGia { get; set; }
    
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
